package Recipt;

import Employee.Employee;
import Products.Product;

import java.util.ArrayList;
import java.util.List;

public class Recipt implements IRecipt{
    private static int counter = 0;
    private int reciptNumber;
    private ArrayList<Product> product;
    private Employee employee;

    public Recipt(){

    }
    public Recipt(Employee employee) {
        this.reciptNumber = counter++;
        this.product = new ArrayList<Product>();
        this.employee = employee;
    }

    public Recipt(Employee employee, ArrayList<Product> allProduct){
        this.reciptNumber = counter++;
        this.product = allProduct;
        this.employee = employee;
    }

    @Override
    public void addProduct(Product product) {
        this.product.add(product);
    }

    @Override
    public double showRecipt() {
        double totalAmount = 0.0;
        System.out.println("----- Recipt No. "+reciptNumber+" -----");
        for (Product prod: product) {
            System.out.println(prod.getProductName()+" --- "+prod.getProductPrice()+" --- "+prod.getProductType());
            totalAmount+=prod.getProductPrice();
        }
        System.out.println("Final Amount: "+totalAmount);
        System.out.println("Generated By: "+employee.getClass().getSimpleName()+" --- "+employee.getEmployeeName());
        return totalAmount;
    }
}
